
default: &default
  user_consumer_key: Pg1MaqymBgzXxtL1r6JWGabCW
  user_consumer_secret: EsVuRYP6mkXL7hO6eqfFouayvEEhESen7EwdLf8RoNANJv4E40
  user_access_token: 920764129-hc4q82PJDunzv4pbU6OMoSw96iPRBubDqCtfg45P
  user_access_token_secret: pF4ihD1GuC08fKiLLZ40cIRkV9d6ufGPYESU7SsF6lVkr"


development:

  secret_key_base: f4c8eacd4018f0e06775de49c9d339435bfefdefd4f20dc7eb18374a600b613f5344d780ff685e0c6900968821686f29478621b47dccebc8f828ff64c4493aa3

test:
  secret_key_base: 482fc54982dbd5b6ebd4e8435e3673973d9cad3ddf92f4897f9c4b602faa4f91c50b40e0a44b5134798e98884252f26103040fce85bdec384c6378d45a0be952


production:
  user_consumer_key:  <%= ENV["USER_CONSUMER_KEY"] %>
  user_consumer_secret:  <%= ENV["USER_CONSUMER_SECRET"] %>
  user_access_token: <%= ENV["USER_ACCESS_TOKEN"] %>
  user_access_token_secret: <%= ENV["USER_ACCESS_TOKEN_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

